version: '3'

services:
  payload:
    build: .
    container_name: payload
    restart: unless-stopped

    ports:
      - '5432:5432'

    environment:
      DATABASE_URI: postgresql://postgres:postgres@postgres:5432/blechregen

    networks:
      - homelab

networks:
  homelab:
    external: true
